# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('lotname', models.CharField(max_length=50, unique=True, verbose_name='ParkingLot Name')),
                ('address', models.CharField(max_length=100, verbose_name='ParkingLot Address')),
                ('total_number', models.CharField(max_length=10, verbose_name='Total Lot Space Number')),
                ('remaining_number', models.CharField(max_length=500, verbose_name='Available Number')),
                ('price_info', models.CharField(max_length=300)),
                ('start_time', models.DateTimeField(verbose_name='Business Time From')),
                ('close_time', models.DateTimeField(verbose_name='Business Time To')),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='UserName')),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
    ]
