# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 05:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_no', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(verbose_name='Reserve from')),
                ('end_time', models.DateTimeField(verbose_name='Reserve to')),
                ('arrive_time', models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0), verbose_name='Arrive at')),
                ('leave_time', models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0), verbose_name='Leave at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Finished?')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.ParkingLot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.User')),
            ],
        ),
    ]
