# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Transaction active?'),
        ),
    ]
